### ISSUE TITLE
How to use with PageView

### ISSUE THREAD

**Issue by Israel001** [littlerobots/flutter-native-state#10]
Please can you show an example of how to use this package with pageview?

**Comment by Israel001** [comment]
This is what I've tried: [https://github.com/Israel001/iSocial/tree/test]() 

When the app opens for the first time, it shows the splash screen and then navigates to the login page, but when user terminates the app by pressing back button and opens it again, the app is suppose to navigate to the login page without showing splash screen (since it's the last route visited before the app was terminated), but this is not the behavior. 

Also, in my app, i am using pageView, so i tried storing the pageIndex into the savedState everytime the page changes, so that when the app is restarted, it can go back to the last page index that the user visited but this doesn't work also.

Please can you look into it?

**Comment by hvisser** [comment]
You seem to be misunderstanding what saving state is in this context. It is only used to restore the app to the exact state where a user left it, after the app was killed by the OS. If you exit the app using the back key, there's actually no state saved by the OS. If you want to skip the splash after the first time it is shown, you should just use a preference to store that.

For the `PageView` listening to changes and then updating the state with `pageIndex` should be the right approach.

**Comment by Israel001** [comment]
Okay, thank you for the clarification. Please is it possible to store values outside ```boolean```, ```string```, ```double``` and ```int``` datatypes? If yes, how?

**Comment by hvisser** [comment]
This isn't really possible due to how the underlying platform works. You should store only small amounts of data in saved state. For example if your app is showing some kind of social media post, you will only want to store the post id in the saved state and get the actual post from a database of a network again vs storing the entire data structure in saved state.
