### ISSUE TITLE
How to save state of a Form,

### ISSUE THREAD

**Issue by samuelezedi** [littlerobots/flutter-native-state#11]
When I'm typing in a form and then I live the app, by the time I return the data is cleared out. how can I save that?

**Comment by hvisser** [comment]
You'll have to update the `SavedStateData` [whenever a change happens to the form fields](https://flutter.dev/docs/cookbook/forms/text-field-changes). To do that you can use the `onChanged` property or use a  `TextEditingController` to listen to the changes. Then in your callback use `SavedState.of(context)` to get the `SavedStateData` and use `putString()` to save the data for with a unique key for each field.

To restore the state you can either use a `StateFullWidget` with the `StateRestoration` mixin or access the `SavedState` directly again to get the saved values.

**Comment by samuelezedi** [comment]
thanks man, I figured it out
