### ISSUE TITLE
State not being saved, main() reruns on app reenter

### ISSUE THREAD

**Issue by greedyRoach** [littlerobots/flutter-native-state#12]
I'm running the code directly from the "example" folder of the plugin (with extra printing, but the code is the same for the purpose of testing)

```

void main() {
  debugPrint("main()");
  runApp(SavedState(child: MyApp()));
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    var savedState = SavedState.of(context);
    debugPrint("rebuild app");

    try {
      debugPrint("\n\nCounter total: ${savedState.getInt('counter')}");
      debugPrint("\n\nSaved: ${savedState.getBool("saved")}");
      debugPrint("\n\nNormal url: ${SavedStateRouteObserver.restoreRoute(savedState)}");
    } catch (e) {
      debugPrint("\n\nError $e");
    }

    // Navigator will set up the correct route history if they are structured in a hierarchical way.
    // See https://api.flutter.dev/flutter/widgets/Navigator/initialRoute.html
    return MaterialApp(
      // for restoring navigator state, you'll need to set a navigator key!
      debugShowCheckedModeBanner: false,
      navigatorKey: GlobalKey(),
      // Setup an observer that will save the current route into the saved state
      navigatorObservers: [SavedStateRouteObserver(savedState: savedState)],
      routes: {
        // If you want to get the saved state passed to your widget, use the builder constructor
        // The SavedState passed in here is "scoped" to this widget; it won't see any of the global state.
        NestedState.route: (context) => SavedState.builder(
            builder: (context, savedState) =>
                NestedState(savedState: savedState)),

        DummyPage.route: (context) => DummyPage(),
      },
      // restore the route or default to the home page
      initialRoute: SavedStateRouteObserver.restoreRoute(savedState) ?? "/",
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> with StateRestoration {
  var _counter = 0;

  void _increment() async {
    _counter++;
    debugPrint('\n\nSaving total');
    await SavedState.of(context).putInt("counter", _counter);
    debugPrint('total saved: ${SavedState.of(context).getInt("counter")}');

    setState(() {});
  }

  @override
  void restoreState(SavedStateData savedState) {
    debugPrint("restoreState: ${savedState.getInt("counter")} ");
    setState(() {
      _counter = savedState.getInt("counter") ?? 0;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            Text('Count = $_counter'),
            MaterialButton(
              child: Text("Increment"),
              onPressed: () => _increment(),
            ),
            LayoutBuilder(
              builder: (context, _) => RaisedButton(
                child: Text("Go"),
                onPressed: () =>
                    Navigator.of(context).pushNamed("/intermediate"),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class DummyPage extends StatelessWidget {
  static const route = "/intermediate";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Another page'),
      ),
      body: RaisedButton(
        child: Text("Onwards"),
        onPressed: () => Navigator.of(context).pushNamed(NestedState.route),
      ),
    );
  }
}

class NestedState extends StatelessWidget {
  static const String route = "/intermediate/nested_state";

  final SavedStateData savedState;
  final bool restoredFromState;

  NestedState({this.savedState}) : this.restoredFromState = savedState.getBool("saved") {
    savedState.putBool("saved", true);
    debugPrint("\n\nsaved state: ${savedState.getBool("saved")}");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: Center(
        child: Text('Restored from state: $restoredFromState'),
      ),
    );
  }
}

```

but after i open a pair of apps and return to the example app, the example resets completely and looks like the app is not saving any kind of state!

![20200525-181658](https://user-images.githubusercontent.com/57685250/82847750-73f61e00-9eb5-11ea-88d4-94665190a825.gif)

this is the console output

<img width="366" alt="Captura de Pantalla 2020-05-25 a la(s) 18 29 14" src="https://user-images.githubusercontent.com/57685250/82847807-d3ecc480-9eb5-11ea-9f21-c7303ac740c9.png">

after the id number of the console changes from 3046 to 3729, the values of the savedStates resets to null

**Comment by greedyRoach** [comment]
Is this the expected behaviour? 
I was expecting the plugin to keept the 'previous' state before android killed the app while being on background. But instead every thing resets, and ended up with the same problem before implementing the plugin
As said before, i am running this directly from the downloaded project of this git repot (just added a bit of extra printing)

**Comment by hvisser** [comment]
The example should obviously work, and last time I checked it did. Make sure you are testing with a full build, not something that is hot reloaded (use `flutter run` from the command line). Main will rerun as the whole app is restarted, this is expected. 

How are you killing the app in the background? You should kill it using the "kill process" button in Android Studio whilst the app is backgrounded. Swiping the app from the tasks will also clear the saved state.

If you still can't get it to work, please share the output of `flutter doctor` and I'll try to reproduce.

**Comment by greedyRoach** [comment]
Hello @hvisser thanks for your time.
I'm running the example with a ``flutter run --release`` with no previously installed apk, so it's one build that is tested.
I'm not killing the process manually, i let the os (android) kill the process. Just like in the gif:

Steps to error
--------

1. Open the app
2. Do something (the example saves the state of the counter)
3. Press "recents button"
4. Open two different apps (this is where i think android kills the app while being on background to save memory)
5. reOpen app from recent apps (the counter restarts at zero, rather than having the previous state)

![20200525-181658](https://user-images.githubusercontent.com/57685250/82909059-64ff8200-9f2e-11ea-8c11-b0e2d2ec453d.gif)

(will post a more clear video, i think i will upload it to youtube)

Notes
--------

- There is something weird, the main() method reruns (as seen in the terminal outputs image)
- The number next to ``I/Flutter (x)`` changes (thats when the main() method reruns, where the savedState restarts?), but i didn't run ``hot reload`` it's the framework itself which reruns the main() method, i touch anything besides the smartphone at that moment
- I'm currently trying to run ``flutter build apk --release``, uninstall the app, reinstall with release apk; but the behavior is the same as in the gif, the os is killing the app, but flutter is not keeping any state (for reference: https://github.com/flutter/flutter/issues/6827 the issue that brought me to your library)

<img width="366" alt="Captura de Pantalla 2020-05-25 a la(s) 18 29 14" src="https://user-images.githubusercontent.com/57685250/82907765-a727c400-9f2c-11ea-8ca1-66183c68ea01.png">

Flutter doctor
--------

<img width="1280" alt="Captura de Pantalla 2020-05-26 a la(s) 8 27 32" src="https://user-images.githubusercontent.com/57685250/82907175-e1449600-9f2b-11ea-9006-6d3153992375.png">

Next steps
--------

I will try to separate the example from the package folder, run it whitout the release flag and kill the process directly with android studio (will post the results in an hour)

i'm almost sure i'm doing something weird, but i have been unable to replicate the library behavior, i don't know why 😟 

Sorry for the weird english and thanks for the patience

**Comment by greedyRoach** [comment]
I did the next 

1. Create new flutter project
2. Move the example code
3. Run with ``flutter run`` 
4. Kill process in android studio
5. Reopen app from "recent apps"

But i had no success either, the state begins as fresh new, no state is saved

Here is the git repo for what i did:
https://github.com/greedyRoach/native_state_test

**Comment by hvisser** [comment]
Thanks for the example project!

I think it's in the way you are testing it. I cannot reproduce the issues you are seeing on the standard example, nor on your project.

There are various ways to "kill" an app and it might depend on your device, but the way to emulate this like it was killed by the OS is:

* Run the app, click the counter a few times
* Background the app by switching to another app or pressing home
* run `adb shell am kill com.example.saved_state_test` from the terminal
* Open the app again from the launcher or recents

Another way to test is to set the developer option for background process limit to allow no background processes. You might want to test this on an emulator and compare it to a real device. 

If your device is killing apps without saving state they you'll probably notice that in other places too.

**Comment by greedyRoach** [comment]
@hvisser thanks a lot man, a lot of help ❤️ 

Indeed this was due to my way of testing the library.

To get the correct behavior i needed to follow the instructions by @hvisser in the previous message

> - Run the app, click the counter a few times
> - Background the app by switching to another app or pressing home
> - Run adb shell am kill com.example.saved_state_test from the terminal
> - Open the app again from the launcher or recents

I proceed to close this issue

**Comment by hvisser** [comment]
No worries, thanks for reporting! It can be hard to test and things might break so I appreciate anyone taking the time to report w/ an example.
