### ISSUE TITLE
Restoring route twice in a row

### ISSUE THREAD

**Issue by leobasilio** [littlerobots/flutter-native-state#16]
Hi. I've just run into an issue that took me a while to figure out. I can only restore the last route once, because of some unexpected behavior in `Navigator`.

When the app is launched, `SavedStateRouteObserver.restoreRoute()` returns `null` as expected. Then I push a new route. The observer is notified and stores the new current route. All right so far. The activity is then destroyed and the app is launched again. At first, `restoreRoute()` returns `null`, but as soon as the state is restored a new build is triggered and we have the correct `/intermediate` value, which is then used as a new initial route for the `MaterialApp`. Now comes the problem. Somehow a `/` route is pushed after that, taking the place of `/intermediate` as the current route in our saved state, despite not showing on the screen. That means that next time `/` will be the restored route, not preserving the state consistently. See the video at the end.

While writing this issue, it crossed my mind that the `Navigator` might be pushing the `/` below the `/intermediate` route to ensure that it will be there once the one on top is popped. I've run the whole test again, now checking for the `route.isCurrent` value. Here's the result:

```
I/flutter ( 5240): build MyApp, restoreRoute = null
I/flutter ( 5240): didPush, route = / route.isCurrent = true
I/flutter ( 5240): build MyApp, restoreRoute = /intermediate
I/flutter ( 5240): didPush, route = /intermediate, route.isCurrent = true
I/flutter ( 5240): didPush, route = /, route.isCurrent = false
```

So indeed that seems to be the case. That means `SavedStateRouteObserver` should take `isCurrent` into account before storing the pushed routed as the current route. Something like:

```dart
@override
void didPush(Route route, Route previousRoute) {
  if(route.isCurrent){
    savedState.putString("_current_route", route?.settings?.name);
  }
}
```

By the way, I'm using Flutter 1.17.5.

![Navigator](https://user-images.githubusercontent.com/16745138/86637544-18d34300-bfac-11ea-9d5c-c2644fb1fdad.gif)

**Comment by hvisser** [comment]
Interesting! Maybe the `Navigator` didn't notify the the observer on restoration before? In any case, good find :)
Considering `route.isCurrent` seems like a good fix for this. PR with the fix and test is welcome here if you want to take a stab at it!
