### ISSUE TITLE
Hot reload causes to rebuild whole application

### ISSUE THREAD

**Issue by rsikk-letsbuild** [littlerobots/flutter-native-state#18]
Hi!

I've run into the issue where hot reload to the application is causing the whole app to reload, meaning the whole widget tree is rebuilding, firing initState() method. Is this expected behavior and is it possible to disable this behavior?

**Comment by hvisser** [comment]
As far as I know, the plugin doesn't affect how hot reload is working. Most likely something else is triggering a rebuild of your widget somehow.
