### ISSUE TITLE
not working for separated widgets 

### ISSUE THREAD

**Issue by salim-lachdhaf** [littlerobots/flutter-native-state#19]
the plugin is not working if the widget (pages) are in separate files, how ever it works only when i pass the savedState of the mainApp as paramater to other pages, but when i use SavedState.of(context).put or .getString it not returning the stored values !

```
class MyApp extends StatelessWidget {
  MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var savedState = SavedState.of(context);
...
```

i'm using generatedRoutes if that could help, also, i tried to pass the builder savedState but not working either.

 ```
case NavigatorRoutes.root_products:
        return MaterialPageRoute(
          settings: RouteSettings(name: NavigatorRoutes.root_products),
          builder: (_) => SavedState.builder(
            builder: (context, savedState) => ProductsWidget(catalogue: args, savedStateData: savedState),
          ),
        );
```

**Comment by hvisser** [comment]
Separated widgets should definitely work, the example actually is using this too. Maybe you don't have a `SavedState` widget in the root of your tree? That would be required, otherwise the `SavedStateData` you create here will be the "root" and will get disposed when the widget is disposed too.

**Comment by salim-lachdhaf** [comment]
i have :
` runApp(SavedState(child: MyApp()));`

**Comment by hvisser** [comment]
OK, like I mentioned https://github.com/littlerobots/flutter-native-state/blob/develop/example/lib/main.dart has the same setup so I don't really know what's going on. Maybe you are expecting state to be saved when it isn't? If you have a small project that reproduces the issue I can take a look.

**Comment by salim-lachdhaf** [comment]
after investigating , 
this when i pass the savedState of the `main` to my widget (correct result)
![image](https://user-images.githubusercontent.com/13780503/95326720-4b3e5600-08a3-11eb-9645-cd711b238b84.png)

and this when i use` SavedState.of(context)`
![Capture1](https://user-images.githubusercontent.com/13780503/95327094-d586ba00-08a3-11eb-862f-cfea0a87d980.PNG)

any solution please ?

**Comment by hvisser** [comment]
If you have a small project that reproduces this issue I can take a look. Based on the above I don't have enough context to see what's going wrong.

**Comment by salim-lachdhaf** [comment]
thank you for your fast feedback
i can describe the app:
Navigation :  `main `-> `catalogue `->`products `
i use generated routes for navigation; example of usage :
 ```
case NavigatorRoutes.root_catalogues:
        return MaterialPageRoute(
          settings: RouteSettings(name: NavigatorRoutes.root_catalogues),
          builder: (_) => SavedState.builder(
            builder: (context, savedState) => CatalogueWidget(),
          ),
        );
case NavigatorRoutes.root_products:
        return MaterialPageRoute(
          settings: RouteSettings(name: NavigatorRoutes.root_products),
          builder: (_) => SavedState.builder(
            builder: (context, savedState) => ProductsWidget(catalogue: args, savedStateData: savedStateData),
          ),
        );
```

that's my main
```

main() async {
    runApp(SavedState(child: MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var savedState = SavedState.of(context);
    // Navigator will set up the correct route history if they are structured in a hierarchical way.
    // See https://api.flutter.dev/flutter/widgets/Navigator/initialRoute.html
    return MaterialApp(
      // for restoring navigator state, you'll need to set a navigator key!
      navigatorKey: GlobalKey(),
      navigatorObservers: [SavedStateRouteObserver(savedState: savedState)],
      // restore the route or default to the home page
      initialRoute: SavedStateRouteObserver.restoreRoute(savedState) ??
          NavigatorRoutes.root,
      home: SplashWidget(),
      onGenerateRoute: (settings) => CustomRouter.generateRoute(savedState, settings),
    );
  }
}
```

**Comment by hvisser** [comment]
Can you provide a Github project of this with exact steps to reproduce?

**Comment by salim-lachdhaf** [comment]
sadly i can't (i will create a sapared project to test the same case)!

i removed 
```
SavedState.builder(
           builder: (context, savedState) => ProductsWidget(catalogue: args, savedStateData: savedStateData),
         ),
```
and it worked !


```
case NavigatorRoutes.root_products:
       return MaterialPageRoute(
         settings: RouteSettings(name: NavigatorRoutes.root_products),
         builder: (_)  => ProductsWidget(catalogue: args, savedStateData: savedStateData),
       );
```

**Comment by hvisser** [comment]
You are using the builder, but passing `savedStateData`, that could be your issue too. You should pass the `savedState` from the builder there.
