### ISSUE TITLE
not working in specific cases

### ISSUE THREAD

**Issue by salim-lachdhaf** [littlerobots/flutter-native-state#20]
i have an app that takes a picture (open new activity camera) and show it. in this case the app restarts and did not restore state, But when i click minimize button and open another app and back to my app the restore works well.

why it did'nt detect in the fisrt case that the app was killed (or whatever it force the restart of the app) and it did in the second case ?

**Comment by salim-lachdhaf** [comment]
update : in both cases the app passes by `inactive`>`paused`>`detached `(`with WidgetsBindingObserver`)

**Comment by hvisser** [comment]
Switching app will most likely not result in your app being killed by the OS. Only if that happened the OS will provide saved state when the app is launched again. Also when testing this make sure to do a full deploy (not a hot reload) to ensure you test with the correct code when the app is launched again. Anything that you hot reload will be gone when the app is killed.

**Comment by salim-lachdhaf** [comment]
to test , i used to enable "don't keep activities" in developer options, and the weired thing that both cases passes by the same states , but one do restart state, and the other no !

i do not use hot reload

**Comment by salim-lachdhaf** [comment]
i found the problem, in the first case before opening the camera activity i used to show a progress dialog, this caused the problem and prevent the restore of the state. I tried opening the camera activity without showing anything (activity 1> camera activity) and the state was restored successfully !
