### ISSUE TITLE
Error on reload

### ISSUE THREAD

**Issue by SergeShkurko** [littlerobots/flutter-native-state#5]
On reload app in debug mode i receive error:
```
Error -32000 received from application: Service protocol could not handle or find a handler for the requested method.
```

**The problem is observed** after a single unloading of the application from memory

Flutter: 1.9.1+hotfix.2

**Comment by hvisser** [comment]
With "unloading" you mean you are killing the app process to test if the state restoration works? 

In that case this is expected, as with the killing of the app process you also kill the hot reload connection that Flutter uses. Flutter does currently not re-establish that connection. 

For the same reason you should make sure to do a full restart of the app when testing state restoration to make sure the deployed code is the initial bundle that is sent to the device.

**Comment by SergeShkurko** [comment]
Understood thanks!
